version: "3.9"

services:

  backend:
    image: nisham1234/e-zone:backend
    container_name: backend_container
    ports:
      - "50001:5000"
    env_file:
      - ./backent/.env
    restart: always

  frontend:
    image: nisham1234/e-zone:frontend
    container_name: frontend_container
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always